#!/bin/bash

# Description: adb logcat -v threadtime -b events (and filters for a specific package name if specified)
# Usage: [PackageName]

if [ $# -gt 1 ] ; then
  echo "Too many arguments!"
  echo "Example 1: rdb elog"
  echo "Example 2: rdb elog com.example.someapp"
elif [ $# -eq 1 ] ; then
  processes=$($ADB $RDB_DEVICE_SELECT shell ps | grep $1)
  if [ -n "$processes" ] ; then
    processes_string=$(echo "$processes" | awk '{print $2"\t"$9}')
    echo -e "$(tput setaf 4)Printing event logs for:\n${processes_string}$(tput sgr0)"
    pid_grep_string=$(echo "$processes" | awk '{print $2}' | sed -e :a -e '$!N;s/\n/|/;ta')
    $ADB $RDB_DEVICE_SELECT logcat -v threadtime -b events | egrep "$pid_grep_string|$1"
  else
    echo "Process "$1" not found or not running!"
  fi
else
  $ADB $RDB_DEVICE_SELECT logcat -v threadtime -b events
fi
