#!/bin/bash

# Description: filters logcat output for a specific package name
# Usage: [PackageName]

package_name=${1:-$RDB_APP_PACKAGE_NAME}
if [ -z $package_name ] ; then
  echo "Please specify a package name: rdb plog [PackageName]"
  echo "Example: rdb plog com.example.someapp"
else
  processes=$($ADB $RDB_DEVICE_SELECT shell ps | grep $package_name)
  if [ -n "$processes" ] ; then
    processes_string=$(echo "$processes" | awk '{print $2"\t"$9}')
    echo -e "$(tput setaf 4)Printing logs for:\n${processes_string}$(tput sgr0)"
    pid_grep_string=$(echo "$processes" | awk '{print $2}' | sed -e :a -e '$!N;s/\n/|/;ta')
    $ADB $RDB_DEVICE_SELECT logcat -v threadtime | egrep "$pid_grep_string"
  else
    echo "Process "$package_name" not found or not running!"
  fi
fi
