#!/bin/bash

# Description: captures screen recording and saves it to the designated path
# Usage: <ScreenRecordingSavePath>

. $RDB_UTIL

remote_screenrecording_file_path="/sdcard/rdb_tmp_screenrecording.mp4"

function pull_recording() {
  sleep 1 &&
  local_screenrecording_save_path=$(append_extension_if_missing ${1%/} mp4)
  $ADB $RDB_DEVICE_SELECT pull ${remote_screenrecording_file_path} ${local_screenrecording_save_path} &&
  $ADB $RDB_DEVICE_SELECT shell rm ${remote_screenrecording_file_path}
  echo -e "\nScreen recording saved to: ${local_screenrecording_save_path}\n"
}

if [ $# -ne 1 ] ; then
  echo "Please specify a save file path for the screen recording: rdb scrp <ScreenRecordingSavePath>"
  echo "Example 1: rdb scr screenrec01.mp4"
  echo "Example 2: rdb scr ~/Desktop/screenrec01.mp4"
  echo "Example 3: rdb scr ~/Desktop/screenrec01   (if missing, '.mp4' will be automatically appended)"
else
  echo "Screen recording has started. $(tput setaf 4)Press Ctrl-C to stop recording...$(tput sgr0)"
  trap "pull_recording $1" EXIT
  $ADB $RDB_DEVICE_SELECT shell screenrecord --bit-rate 16000000 ${remote_screenrecording_file_path}
fi
