#!/bin/bash

# Description: checks whether your git working directory has any staged but uncommitted changes (using git diff-index)

git rev-parse --verify HEAD >/dev/null || exit 1
git update-index -q --ignore-submodules --refresh

if ! git diff-index --cached --quiet --ignore-submodules HEAD -- ; then
  echo >&2 "Your index contains uncommitted changes."
  exit 1
fi
