#!/bin/bash

# Description: checks whether your git working directory has any unstaged changes (using git diff-files)

git rev-parse --verify HEAD >/dev/null || exit 1
git update-index -q --ignore-submodules --refresh

if ! git diff-files --quiet --ignore-submodules ; then
  echo >&2 "You have unstaged changes."
  exit 1
fi
