#!/bin/bash

# Description: display this manual in markdown format

num_cmds=0
for command in $(find ${RDB_COMMANDS_PATH} -type f | grep -v '/\.' | awk -F'/' '{print($NF"/"$0)}' | sort -k1n,1n -t'/' | cut -f2- -d'/')
do
  cmds[num_cmds]=${command##*/}
  usage_strings[num_cmds]=$(sed -n 's/ *# *Usage *: *\(.*\)/\1/p' $command | sed 's/\([<\|>]\)/\\\1/g')
  description_strings[num_cmds]=$(sed -n 's/ *# *Description *: *\(.*\)/\1/p' $command | sed 's/\([<\|>]\)/\\\1/g')
  (( num_cmds++ ))
done

echo -e "# ${RDB_BASE_NAME} v${RDB_VERSION}\n"
echo "## Usage"
echo -e "${RDB_BASE_NAME} [OPTIONS] \<COMMAND\>\n"
echo "## Options"
echo "Option | Parameters | Description"
echo "-----: | :--------- | :----------"
printf "%s | %s | %s\n" "-s" "[DeviceSerialNumber]" "sends the command to the specified device"
printf "%s | %s | %s\n" "-a" "" "sends the command to all connected devices (this will override -s)"
echo -e "\n## Commands"
echo "Command | Parameters | Description"
echo "------: | :--------- | :----------"
for (( i=0 ; i<$num_cmds ; i++ ))
do
  printf "%s | %s | %s\n" "${cmds[i]}" "${usage_strings[i]}" "${description_strings[i]}"
done
echo
