#!/bin/bash

# Description: adb shell getprop (and filters using a search string if specified)
# Usage: [SearchString]

if [ $# -gt 1 ] ; then
  echo "Too many arguments!"
  echo "Example 1: rdb gp"
  echo "Example 2: rdb gp ro.build"
elif [ $# -eq 1 ] ; then
  adb $RDB_DEVICE_SELECT shell getprop | egrep -i "$@"
else
  adb $RDB_DEVICE_SELECT shell getprop
fi
