#!/bin/bash

# Description: get PID (process id) by full or partial package name
# Usage: [PackageName|SearchString]

package_name=${1:-$RDB_APP_PACKAGE_NAME}
if [ -z $package_name ] ; then
  echo "Please specify a package name or a search string: rdb pid [PackageName|SearchString]"
  echo "Example 1: rdb pid com.example.someapp"
  echo "Example 2: rdb pid someapp"
else
  pid=$($ADB $RDB_DEVICE_SELECT shell ps | grep $package_name | awk '{print $2"\t"$9}')
  if [ -n "$pid" ] ; then
    echo -e "PID(s) found for '$package_name':\n$pid"
  else
    echo "Process '"$package_name"' not found!"
  fi
fi
